### ISSUE TITLE
The web interface has an undefined error after the one-line install on Debian 10.

### ISSUE THREAD

**Issue by poikilos** [sbs20/scanservjs#198]
**Describe the bug**
The web interface has an undefined error.

**To Reproduce**
1. Run one-line install
2. Go to the web interface (remotely via LAN in my case)

**Expected behavior**
- Show specific error instead of "undefined" in the web interface
- The systemd unit should provide correct status via systemctl instead of saying not running when is running
- not restart rapidly

**Screenshots**

**Client (please complete the following information):**

- Browser: Brave
- Version 1.22.70 Chromium: 89.0.4389.105 (Official Build) (64-bit)
 
**Server (please complete the following information):**
 - OS: Debian 10
 - Node version 10.24.0
 - NPM version 7.10.0
 - Docker version N/A

**Logs**
 - Please include application logs (see commands below)
 
This may be useful

# Logs if installed manually
`sudo journalctl | grep server.js > scanservjs.log.installed.txt`
See below.

# Logs if in docker
`docker logs scanservjs-container > scanservjs.log.docker.txt`
n/a

**Additional context**
After running the one line install, there are no errors other than (minor?) npm warnings:
```
. . .
npm WARN npm npm does not support Node.js v10.24.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
/usr/local/bin/npx -> /usr/local/lib/node_modules/npm/bin/npx-cli.js
npm WARN npm@7.10.0 had bundled packages that do not match the required version(s). They have been replaced with non-bundled versions.

+ npm@7.10.0
added 252 packages from 909 contributors in 16.492s
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   646  100   646    0     0   5209      0 --:--:-- --:--:-- --:--:--  5209
100 2723k  100 2723k    0     0  6190k      0 --:--:-- --:--:-- --:--:-- 6190k
npm WARN npm npm does not support Node.js v10.24.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
added 68 packages from 46 contributors in 2.073s
Created symlink /etc/systemd/system/multi-user.target.wants/scanservjs.service → /etc/systemd/system/scanservjs.service.
scanservjs installed and running
http://127.0.0.1:8080

If you have problems, try 'sudo journalctl -e -u scanservjs'
```

But upon visiting the web interface there are two red popups immediately after loading:

1:

> Found no devices

2:

> {"message":"Cannot read property 'features' of undefined", "code":-1}

I reinstalled recently (Debian 10), but scanimage -L shows 
```
device `brother4:net1;dev0' is a Brother MFC-L2740DW MFC-L2740DW
device `brother4:bus2;dev3' is a Brother MFC-L2740DW USB scanner
```

If I run the journalctl command, the log shows that the process keeps restarting over and over rapidly:
```
Apr 17 08:04:21 birdo server.js[4601]:     at startup (internal/bootstrap/node.js:283:19)
Apr 17 08:04:21 birdo server.js[4601]:     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
Apr 17 08:04:21 birdo systemd[1]: scanservjs.service: Main process exited, code=exited, status=1/FAILURE
Apr 17 08:04:21 birdo systemd[1]: scanservjs.service: Failed with result 'exit-code'.
Apr 17 08:04:21 birdo systemd[1]: scanservjs.service: Service RestartSec=100ms expired, scheduling restart.
Apr 17 08:04:21 birdo systemd[1]: scanservjs.service: Scheduled restart job, restart counter is at 4.
Apr 17 08:04:21 birdo systemd[1]: Stopped scanservjs.
Apr 17 08:04:21 birdo systemd[1]: Started scanservjs.
Apr 17 08:04:21 birdo server.js[4609]: events.js:174
Apr 17 08:04:21 birdo server.js[4609]:       throw er; // Unhandled 'error' event
Apr 17 08:04:21 birdo server.js[4609]:       ^
Apr 17 08:04:21 birdo server.js[4609]: Error: listen EADDRINUSE: address already in use :::8080
Apr 17 08:04:21 birdo server.js[4609]:     at Server.setupListenHandle [as _listen2] (net.js:1280:14)
Apr 17 08:04:21 birdo server.js[4609]:     at listenInCluster (net.js:1328:12)
Apr 17 08:04:21 birdo server.js[4609]:     at Server.listen (net.js:1415:7)
Apr 17 08:04:21 birdo server.js[4609]:     at Function.listen (/var/www/scanservjs/node_modules/express/lib/application.js:618:24)
Apr 17 08:04:21 birdo server.js[4609]:     at Object.<anonymous> (/var/www/scanservjs/server/server.js:13:5)
Apr 17 08:04:21 birdo server.js[4609]:     at Module._compile (internal/modules/cjs/loader.js:778:30)
Apr 17 08:04:21 birdo server.js[4609]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
Apr 17 08:04:21 birdo server.js[4609]:     at Module.load (internal/modules/cjs/loader.js:653:32)
Apr 17 08:04:21 birdo server.js[4609]:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
Apr 17 08:04:21 birdo server.js[4609]:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
Apr 17 08:04:21 birdo server.js[4609]: Emitted 'error' event at:
Apr 17 08:04:21 birdo server.js[4609]:     at emitErrorNT (net.js:1307:8)
Apr 17 08:04:21 birdo server.js[4609]:     at process._tickCallback (internal/process/next_tick.js:63:19)
Apr 17 08:04:21 birdo server.js[4609]:     at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
Apr 17 08:04:21 birdo server.js[4609]:     at startup (internal/bootstrap/node.js:283:19)
Apr 17 08:04:21 birdo server.js[4609]:     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
Apr 17 08:04:21 birdo systemd[1]: scanservjs.service: Main process exited, code=exited, status=1/FAILURE
Apr 17 08:04:21 birdo systemd[1]: scanservjs.service: Failed with result 'exit-code'.
Apr 17 08:04:22 birdo systemd[1]: scanservjs.service: Service RestartSec=100ms expired, scheduling restart.
Apr 17 08:04:22 birdo systemd[1]: scanservjs.service: Scheduled restart job, restart counter is at 5.
Apr 17 08:04:22 birdo systemd[1]: Stopped scanservjs.
Apr 17 08:04:22 birdo systemd[1]: scanservjs.service: Start request repeated too quickly.
Apr 17 08:04:22 birdo systemd[1]: scanservjs.service: Failed with result 'exit-code'.
Apr 17 08:04:22 birdo systemd[1]: Failed to start scanservjs.
```

If I run `sudo systemctl status scanservjs` it says "Active: failed" (not running; even though the web interface displays--so the systemd unit seems to be reporting the status incorrectly)

If I visit the web interface, it is still up and shows the 2 red popups again. However, no new entries appear in journalctl after that.

**Comment by poikilos** [comment]
:( I forgot I installed the docker version already.  I will uninstall that and reboot.

**Comment by poikilos** [comment]
The undefined error turns out to be from the docker install since that was the only one actually running. See #202.
