### ISSUE TITLE
Configurable request timeout for scan

### ISSUE THREAD

**Issue by szhem** [sbs20/scanservjs#306]
**Describe the bug**
When scanning files with high resolution, e.g. 1200dpi it is very likely for the request to timeout in case of default node http server [2 mins](https://nodejs.org/dist/latest-v6.x/docs/api/http.html#http_server_timeout).
After timeout application tries to create preview image but it cannot as image does not exist at this moment, so the application fails with the error like the following:

**To Reproduce**
1. Open the application
2. Select the highest resolution possible
3. Click scan
4. Wait for more than 2 minutes
5. See error

In case the error will not appear you can try to decrease timeout like the following

```
    const server = app.listen(Config.port, () => {  
        log.info('Started');
    });
    server.setTimeout(5000);
```

**Expected behavior**
Application wait until scan completes and not fails.

**Server (please complete the following information):**
 - OS: PRETTY_NAME="Debian GNU/Linux bullseye/sid"; NAME="Debian GNU/Linux"; ID=debian; HOME_URL="https://www.debian.org/"; SUPPORT_URL="https://www.debian.org/support"; BUG_REPORT_URL="https://bugs.debian.org/"
 - Node version: v12.21.0
 - NPM version: 7.11.2
 - Docker version [e.g. 19]

**Logs**
 - Please include application logs (see commands below)
 
```
[2021-06-15T08:21:21.794Z] DEBUG (Scan): Post processing: PNG
[2021-06-15T08:21:21.811Z] DEBUG (Process): /usr/bin/convert 'data/temp/~tmp-scan-0-0001.tif' -background '#808080' -extent '10157.48031496063x14031.496062992126-0-0' -resize 868 'data/preview/preview.tif',  undefined , 
{"encoding":"binary","shell":true,"maxBuffer":16384,"ignoreErrors":false}
[2021-06-15T08:21:21.825Z] ERROR (Http): Error: /usr/bin/convert 'data/temp/~tmp-scan-0-0001.tif' -background '#808080' -extent '10157.48031496063x14031.496062992126-0-0' -resize 868 'data/preview/preview.tif' exited with code: 1, stderr: convert: Cannot read TIFF header. `data/temp/~tmp-scan-0-0001.tif' @ error/tiff.c/TIFFErrors/606.
convert: no images defined `data/preview/preview.tif' @ error/convert.c/ConvertImageCommand/3229.
    
    at ChildProcess.<anonymous> (/var/www/scanservjs/server/process.js:54:18)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
```

**Additional context**

The fix like the following helps to avoid the error.

    const server = app.listen(Config.port, () => {  
        log.info('Started');
    });
    server.setTimeout(600000);

**Comment by sbs20** [comment]
I've made this configurable - but left the default as 120000. You will need to override it in config.local.js.

Thanks for raising and providing a fix and making my life easier!
