### ISSUE TITLE
Ignoring net:scanner.<>:epjitsu:libusb:001:003. Error: -l is missing from device  (FUJITSU ScanSnap S1300i)

### ISSUE THREAD

**Issue by coolnovember** [sbs20/scanservjs#350]
I am trying to configure my FUJITSU ScanSnap S1300i scanner as a Network scanner using SaneOverNetwork.

I see the following error message . What is a -l , and how do I add it?

```
Sep 01 14:52:47 printnscan server.js[1614]: [2021-09-01T14:52:47.063Z] DEBUG (Http): request:  { method: 'POST', path: '/preview' }
Sep 01 14:52:47 printnscan server.js[1614]: [2021-09-01T14:52:47.064Z] DEBUG (Devices): devices.json contains no devices. Reloading
Sep 01 14:52:47 printnscan server.js[1614]: [2021-09-01T14:52:47.064Z] DEBUG (Devices): Config.devices:  []
Sep 01 14:52:57 printnscan server.js[1614]: [2021-09-01T14:52:57.230Z] DEBUG (Devices): Device list:  device `net:scanner.lan.greenrobin.net:epjitsu:libusb:001:003' is a FUJITSU ScanSnap S1300i scanner
Sep 01 14:52:57 printnscan server.js[1614]: [2021-09-01T14:52:57.264Z] DEBUG (Devices): Device features:
Sep 01 14:52:57 printnscan server.js[1614]: All options specific to device `net:scanner.lan.greenrobin.net:epjitsu:libusb:001:003':
Sep 01 14:52:57 printnscan server.js[1614]:   Scan Mode:
Sep 01 14:52:57 printnscan server.js[1614]:     --source ADF Front|ADF Back|ADF Duplex [ADF Front]
Sep 01 14:52:57 printnscan server.js[1614]:         Selects the scan source (such as a document-feeder).
Sep 01 14:52:57 printnscan server.js[1614]:     --mode Lineart|Gray|Color [Lineart]
Sep 01 14:52:57 printnscan server.js[1614]:         Selects the scan mode (e.g., lineart, monochrome, or color).
Sep 01 14:52:57 printnscan server.js[1614]:     --resolution 50..600dpi (in steps of 1) [300]
Sep 01 14:52:57 printnscan server.js[1614]:         Sets the resolution of the scanned image.
Sep 01 14:52:57 printnscan server.js[1614]:   Geometry:
Sep 01 14:52:57 printnscan server.js[1614]:     -t 0..289.353mm (in steps of 0.0211639) [0]
Sep 01 14:52:57 printnscan server.js[1614]:         Top-left y position of scan area.
Sep 01 14:52:57 printnscan server.js[1614]:     --page-width 2.70898..219.428mm (in steps of 0.0211639) [215.872]
Sep 01 14:52:57 printnscan server.js[1614]:         Specifies the width of the media.  Required for automatic centering of
Sep 01 14:52:57 printnscan server.js[1614]:         sheet-fed scans.
Sep 01 14:52:57 printnscan server.js[1614]:     --page-height 0..450.707mm (in steps of 0.0211639) [292.062]
Sep 01 14:52:57 printnscan server.js[1614]:         Specifies the height of the media, 0 will auto-detect.
Sep 01 14:52:57 printnscan server.js[1614]:   Enhancement:
Sep 01 14:52:57 printnscan server.js[1614]:     --brightness -127..127 (in steps of 1) [0]
Sep 01 14:52:57 printnscan server.js[1614]:         Controls the brightness of the acquired image.
Sep 01 14:52:57 printnscan server.js[1614]:     --contrast -127..127 (in steps of 1) [0]
Sep 01 14:52:57 printnscan server.js[1614]:         Controls the contrast of the acquired image.
Sep 01 14:52:57 printnscan server.js[1614]:     --threshold 0..255 (in steps of 1) [120]
Sep 01 14:52:57 printnscan server.js[1614]:         Select minimum-brightness to get a white point
Sep 01 14:52:57 printnscan server.js[1614]:     --threshold-curve 0..127 (in steps of 1) [55]
Sep 01 14:52:57 printnscan server.js[1614]:         Dynamic threshold curve, from light to dark, normally 50-65
Sep 01 14:52:57 printnscan server.js[1614]:   Sensors:
Sep 01 14:52:57 printnscan server.js[1614]:     --scan[=(yes|no)] [no] [hardware]
Sep 01 14:52:57 printnscan server.js[1614]:         Scan button
Sep 01 14:52:57 printnscan server.js[1614]:     --page-loaded[=(yes|no)] [no] [hardware]
Sep 01 14:52:57 printnscan server.js[1614]:         Page loaded
Sep 01 14:52:57 printnscan server.js[1614]:     --top-edge[=(yes|no)] [no] [hardware]
Sep 01 14:52:57 printnscan server.js[1614]:         Paper is pulled partly into adf
Sep 01 14:52:57 printnscan server.js[1614]:     --cover-open[=(yes|no)] [no] [hardware]
Sep 01 14:52:57 printnscan server.js[1614]:         Cover open
Sep 01 14:52:57 printnscan server.js[1614]:     --power-save[=(yes|no)] [no] [hardware]
Sep 01 14:52:57 printnscan server.js[1614]:         Scanner in power saving mode
Sep 01 14:52:57 printnscan server.js[1614]: [2021-09-01T14:52:57.265Z] ERROR (Devices): Ignoring net:scanner.lan.greenrobin.net:epjitsu:libusb:001:003. Error: -l is missing from device

```
The actual net export works. I can see this calling scanimage directly

```
scanimage -L
device `net:scanner.lan.greenrobin.net:epjitsu:libusb:001:003' is a FUJITSU ScanSnap S1300i scanner

```

Running scan image locally, does produce images

```

me@printnscan:~$ scanimage --source "ADF Duplex"  --mode Color --resolution 300 -p --format tiff -b
Scanning infinity pages, incrementing by 1, numbering from 1
Scanning page 1
Scanned page 1. (scanner status = 5)
Scanning page 2
Scanned page 2. (scanner status = 5)
Scanning page 3
scanimage: sane_start: Document feeder out of documents
Batch terminated, 2 pages scanned


```

ScanServer Machine
```
me@printnscan:~$ uname -a
Linux printnscan 5.4.78-2-pve #1 SMP PVE 5.4.78-2 (Thu, 03 Dec 2020 14:26:17 +0100) x86_64 x86_64 x86_64 GNU/Linux

me@printnscan:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"

```

Network SANE server

```
mex@scanner:$ uname -a
Linux scanner 5.4.0-81-generic #91-Ubuntu SMP Thu Jul 15 19:09:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
mex@scanner:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"

```

**Comment by coolnovember** [comment]
poking around the source, it seems to come from

scanservjs/packages/server/src/device.js  

Line 158 - 

https://github.com/sbs20/scanservjs/blob/c36cabcf6a31ba246b232aeecc6a1f2cbc108532/packages/server/src/device.js#L158
```

  validate() {
    const mandatory = ['--resolution', '-l', '-t', '-x', '-y'];
    for (const feature of mandatory) {
      if (this.features[feature] === undefined) {
        throw `${feature} is missing from device`;
      }
    }
  }
```

My scanner does not seem to support a -l option (it does support a -t)

**Comment by sbs20** [comment]
Oh! Not seen that one before. Thanks for reporting, I'll take a look.

**Comment by ebretteville** [comment]
I have the same scanne fujitsu S13OOi conected to USB, sane is working but no scanner found in the webui, how can I test a version with the 9acdf3b commit?

**Comment by sbs20** [comment]
Hi. If you're getting device not found, then that commit won't help. The commit only fixes `Error: -l is missing from device`

Device not found means that the software can't see the scanner at all. This might be helpful https://github.com/sbs20/scanservjs/blob/master/docs/sane.md#validate-sane-is-working

Depending how you're running (docker or manual) it might be worth looking at those docs too.

**Comment by ebretteville** [comment]
I did tried everything under the link. And it works. But  no scanners found in the webui....

**Comment by sbs20** [comment]
What about: `sudo su - scanservjs -c 'scanimage -L'`

**Comment by ebretteville** [comment]
```
pi@scan-sane:~ $ sudo su - scanservjs -c 'scanimage -L'
device `epjitsu:libusb:001:002' is a FUJITSU ScanSnap S1300i scanner
pi@scan-sane:~ $
```

**Comment by sbs20** [comment]
Ok. Please open a new issue and supply the logs and if possible a screen grab of the error.

**Comment by ebretteville** [comment]
done

**Comment by jhenkens** [comment]
Playing around with the development branch - have my scanner detecting and semi-working now, after hitting the `-l` error. Hit scan, and it fails here: `https://github.com/sbs20/scanservjs/blob/master/packages/server/src/scan-controller.js#L135`.

I added the following config (fixes this width/height issue, as well as having a name, otherwise it'd show `[Object object]` as the name).

```
module.exports = {
  /**
   * @param {Configuration} config
   */
  afterConfig(config) {
  },

  /**
   * @param {ScanDevice[]} devices
   */
  afterDevices(devices) {
    const deviceNames = {
      'epjitsu:libusb:001:007': 'Fujitsu ScanSnap s1300'
    };

    devices
      .filter(d => d.id in deviceNames)
      .forEach(d => {
        d.name = deviceNames[d.id];
        d.features['-l'] = d.features['-l'] || {};
        d.features['-l'].limits = [0, 215];
        // d.features['-t'].limits = [0, 297];
        d.features['-x'] = d.features['-x'] || {};
        d.features['-x'].default = 215;
        d.features['-x'].limits = [0, 215];

        d.features['-y'] = d.features['-y'] || {};
        d.features['-y'].default = 297;
        d.features['-y'].limits = [0, 297];
      });
  }
};
```

Device before setting via customizations:

```
{
    "id": "epjitsu:libusb:001:007",
    "features": {
        "--source": {
            "text": "--source ADF Front|ADF Back|ADF Duplex [ADF Front]",
            "name": "--source",
            "default": "ADF Front",
            "parameters": "ADF Front|ADF Back|ADF Duplex",
            "options": [
                "ADF Front",
                "ADF Back",
                "ADF Duplex"
            ]
        },
        "--mode": {
            "text": "--mode Lineart|Gray|Color [Lineart]",
            "name": "--mode",
            "default": "Lineart",
            "parameters": "Lineart|Gray|Color",
            "options": [
                "Lineart",
                "Gray",
                "Color"
            ]
        },
        "--resolution": {
            "text": "--resolution 50..600dpi (in steps of 1) [300]",
            "name": "--resolution",
            "default": 300,
            "parameters": "50..600dpi (in steps of 1)",
            "limits": [
                50,
                600
            ],
            "interval": 1,
            "options": [
                50,
                75,
                150,
                300,
                600
            ]
        },
        "-t": {
            "text": "-t 0..289.353mm (in steps of 0.0211639) [0]",
            "name": "-t",
            "default": 0,
            "parameters": "0..289.353mm (in steps of 0.0211639)",
            "limits": [
                0,
                289.3
            ],
            "interval": 0.0211639
        },
        "--page-width": {
            "text": "--page-width 2.70898..219.428mm (in steps of 0.0211639) [215.872]",
            "name": "--page-width",
            "default": "215.872",
            "parameters": "2.70898..219.428mm (in steps of 0.0211639)"
        },
        "--page-height": {
            "text": "--page-height 0..450.707mm (in steps of 0.0211639) [292.062]",
            "name": "--page-height",
            "default": "292.062",
            "parameters": "0..450.707mm (in steps of 0.0211639)"
        },
        "--brightness": {
            "text": "--brightness -127..127 (in steps of 1) [0]",
            "name": "--brightness",
            "default": 0,
            "parameters": "-127..127 (in steps of 1)",
            "limits": [
                -127,
                127
            ],
            "interval": 1
        },
        "--contrast": {
            "text": "--contrast -127..127 (in steps of 1) [0]",
            "name": "--contrast",
            "default": 0,
            "parameters": "-127..127 (in steps of 1)",
            "limits": [
                -127,
                127
            ],
            "interval": 1
        },
        "--threshold": {
            "text": "--threshold 0..255 (in steps of 1) [120]",
            "name": "--threshold",
            "default": "120",
            "parameters": "0..255 (in steps of 1)"
        },
        "--threshold-curve": {
            "text": "--threshold-curve 0..127 (in steps of 1) [55]",
            "name": "--threshold-curve",
            "default": "55",
            "parameters": "0..127 (in steps of 1)"
        },
        "--scan": {
            "text": "--scan[=(yes|no)] [no] [hardware]",
            "name": "--scan",
            "default": "hardware",
            "parameters": "[=(yes|no)] [no]"
        },
        "--page-loaded": {
            "text": "--page-loaded[=(yes|no)] [no] [hardware]",
            "name": "--page-loaded",
            "default": "hardware",
            "parameters": "[=(yes|no)] [no]"
        },
        "--top-edge": {
            "text": "--top-edge[=(yes|no)] [no] [hardware]",
            "name": "--top-edge",
            "default": "hardware",
            "parameters": "[=(yes|no)] [no]"
        },
        "--cover-open": {
            "text": "--cover-open[=(yes|no)] [no] [hardware]",
            "name": "--cover-open",
            "default": "hardware",
            "parameters": "[=(yes|no)] [no]"
        },
        "--power-save": {
            "text": "--power-save[=(yes|no)] [yes] [hardware]",
            "name": "--power-save",
            "default": "hardware",
            "parameters": "[=(yes|no)] [yes]"
        }
    },
    "string": "\nAll options specific to device `epjitsu:libusb:001:007':\n  Scan Mode:\n    --source ADF Front|ADF Back|ADF Duplex [ADF Front]\n        Selects the scan source (such as a document-feeder).\n    --mode Lineart|Gray|Color [Lineart]\n        Selects the scan mode (e.g., lineart, monochrome, or color).\n    --resolution 50..600dpi (in steps of 1) [300]\n        Sets the resolution of the scanned image.\n  Geometry:\n    -t 0..289.353mm (in steps of 0.0211639) [0]\n        Top-left y position of scan area.\n    --page-width 2.70898..219.428mm (in steps of 0.0211639) [215.872]\n        Specifies the width of the media.  Required for automatic centering of\n        sheet-fed scans.\n    --page-height 0..450.707mm (in steps of 0.0211639) [292.062]\n        Specifies the height of the media, 0 will auto-detect.\n  Enhancement:\n    --brightness -127..127 (in steps of 1) [0]\n        Controls the brightness of the acquired image.\n    --contrast -127..127 (in steps of 1) [0]\n        Controls the contrast of the acquired image.\n    --threshold 0..255 (in steps of 1) [120]\n        Select minimum-brightness to get a white point\n    --threshold-curve 0..127 (in steps of 1) [55]\n        Dynamic threshold curve, from light to dark, normally 50-65\n  Sensors:\n    --scan[=(yes|no)] [no] [hardware]\n        Scan button\n    --page-loaded[=(yes|no)] [no] [hardware]\n        Page loaded\n    --top-edge[=(yes|no)] [no] [hardware]\n        Paper is pulled partly into adf\n    --cover-open[=(yes|no)] [no] [hardware]\n        Cover open\n    --power-save[=(yes|no)] [yes] [hardware]\n        Scanner in power saving mode\n\n"
}```

**Comment by jhenkens** [comment]
A document scanner like this - I'm not sure the value of having a "preview" mode, as the document must be re-loaded into the feeder to scan again.

**Comment by ebretteville** [comment]
> A document scanner like this - I'm not sure the value of having a "preview" mode, as the document must be re-loaded into the feeder to scan again.

+1, as in fact you have to place the sheet back into the feeder

**Comment by sbs20** [comment]
Hi @jhenkens - any chance you could retest whenever you get a chance? Sorry - I don't have a scanner with these features.

* No longer shows preview button if geometry is unavailable (doc scanners)
* Device name should get populated with default value
* Hopefully no more issues with errors for geometry params

**Comment by jhenkens** [comment]
Much improved, not quite there yet!

Before:
![image](https://user-images.githubusercontent.com/242763/135298066-da752c0a-e3dc-4575-966c-b9be35b6f6e5.png)

After (with all config removed):
![image](https://user-images.githubusercontent.com/242763/135298100-195a59a7-2d22-4c01-a477-75e938e10afe.png)

However, when I hit scan:
![Screen Shot 2021-09-29 at 8 14 25 AM](https://user-images.githubusercontent.com/242763/135298138-3525bab9-b958-4297-ab32-3d5467aaa18b.png)

```
[2021-09-29T15:14:17.165Z] DEBUG (Scan): Post processing: PDF (JPG | @:pipeline.low-quality)
[2021-09-29T15:14:17.184Z] DEBUG (Process): [object Object],  undefined , {"encoding":"binary","shell":true,"maxBuffer":16384,"ignoreErrors":false}
[2021-09-29T15:14:17.186Z] ERROR (Http): TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received an instance of CmdBuilder
    at new NodeError (internal/errors.js:322:7)
    at validateString (internal/validators.js:124:11)
    at normalizeSpawnArguments (child_process.js:486:3)
    at spawn (child_process.js:653:13)
    at spawnWithSignal (child_process.js:911:17)
    at /app/server/process.js:36:20
    at new Promise (<anonymous>)
    at Object.spawn (/app/server/process.js:33:18)
    at ScanController.updatePreview (/app/server/scan-controller.js:150:19)
    at ScanController.finish (/app/server/scan-controller.js:76:16) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by sbs20** [comment]
Argh - sorry, my bad. I am old enough not to be making mistakes like this. Fix coming.

**Comment by sbs20** [comment]
Maybe now? I think I'm going to have to try and get hold of a document scanner!

**Comment by jhenkens** [comment]
Seems to work great! And please, don't be hard on yourself - fixing an open source project that requires hardware to properly test that you don't even have! Excellent work. Absolutely love untethering my scanner from my laptop. Also means that I know it will work "forever", regardless of OS updates, since its all just a docker container.

**Comment by sbs20** [comment]
Ha - thank you, that's very gracious of you. I was only hard on myself because I didn't test it properly even with the hardware I **do** have!!

**Comment by ebretteville** [comment]
Tried with a recent pull, here is my error message after one success scan (paper gone through the scan but no picture: but next scan:`
{"message":"/usr/bin/scanimage -d 'epjitsu:libusb:001:004' --mode 'Lineart' --source 'ADF Front' --resolution 300 --format 'tiff' --brightness 0 --contrast 0 > data/temp/~tmp-scan-0-0001.tif exited with code: 1, stderr: scanimage: open of device epjitsu:libusb:001:004 failed: Invalid argument\n","code":-1}`

**Comment by sbs20** [comment]
Try using auto batch.

If that doesn't work, try experimenting with the command line, just to exclude scanservjs:

```
/usr/bin/scanimage -d 'epjitsu:libusb:001:004' --mode 'Lineart' --source 'ADF Front' --resolution 300 --format 'tiff' --brightness 0 --contrast 0 > test1.tif
```

**Comment by ebretteville** [comment]
```
pi@scan-sane:~ $ sudo scanimage -L
device `epjitsu:libusb:001:005' is a FUJITSU ScanSnap S1300i scanner
pi@scan-sane:~ $ /usr/bin/scanimage -d 'epjitsu:libusb:001:004' --mode 'Lineart' --source 'ADF Front' --resolution 300 --format 'tiff' --brightness 0 --contrast 0 > test1.tif
scanimage: open of device epjitsu:libusb:001:004 failed: Invalid argument
pi@scan-sane:~ $
```

**Comment by sbs20** [comment]
I'm afraid this is beyond me now. You'll need to do a search yourself on these error messages and focus on scanimage. Possible causes might be an old sane version (you might be able to install a newer version) or maybe a driver. Search for "pi" and your scanner model.

**Comment by coolnovember** [comment]
Thank you so much for working on this! Unfortunately, the staging branch does not seem to work for me (as of today Oct-2)
I get the same -l missing from device.

```
Oct 02 17:21:15 printnscan server.js[18449]: [2021-10-02T22:21:15.056Z] ERROR (Devices): Ignoring net:scanner.lan.greenrobin.net:epjitsu:libusb:001:008. Error: -l is missing from device
Oct 02 17:21:15 printnscan server.js[18449]: [2021-10-02T22:21:15.072Z] DEBUG (Http): request:  { method: 'POST', path: '/preview' }
Oct 02 17:21:15 printnscan server.js[18449]: [2021-10-02T22:21:15.072Z] DEBUG (Devices): devices.json contains no devices. Reloading
Oct 02 17:21:15 printnscan server.js[18449]: [2021-10-02T22:21:15.072Z] DEBUG (Devices): Config.devices:  []

```
I am running the staging branch.

```
commit 3a59ab0e6f77b7b3df19474ef69e330e69c8a35a (HEAD -> staging, origin/staging)
Merge: f53cc3b 180ee41
Author: Sam Strachan <sam.strachan@gmail.com>
Date:   Wed Sep 29 21:07:49 2021 +0100

    Merge pull request #361 from sbs20/development

    Localisation & optional geometry

```

**Comment by sbs20** [comment]
@coolnovember no problem, can you provide more logs / info please? There's not enough info to tell what's happening

**Comment by coolnovember** [comment]
Its basically the same error as last time. It sees the scanner remote, but still looks like its trying to use the -l parameter?
I've restarted the service (installed via the installer in the package)

```
Oct 02 17:36:19 printnscan systemd[1]: Stopped scanservjs.
Oct 02 17:36:19 printnscan systemd[1]: Started scanservjs.
Oct 02 17:36:19 printnscan server.js[18540]: [2021-10-02T22:36:19.680Z] INFO (server): Started
Oct 02 17:36:40 printnscan server.js[18540]: [2021-10-02T22:36:40.483Z] DEBUG (Http): request:  { method: 'GET', path: '/context' }
Oct 02 17:36:40 printnscan server.js[18540]: [2021-10-02T22:36:40.485Z] DEBUG (Devices): devices.json contains no devices. Reloading
Oct 02 17:36:40 printnscan server.js[18540]: [2021-10-02T22:36:40.485Z] DEBUG (Devices): Config.devices:  []
Oct 02 17:36:50 printnscan server.js[18540]: [2021-10-02T22:36:50.682Z] DEBUG (Devices): Device list:  device `net:scanner.lan.greenrobin.net:epjitsu:libusb:001:008' is a FUJITSU ScanSnap S1300i scanner
Oct 02 17:36:50 printnscan server.js[18540]: [2021-10-02T22:36:50.772Z] DEBUG (Devices): Device features:
Oct 02 17:36:50 printnscan server.js[18540]: All options specific to device `net:scanner.lan.greenrobin.net:epjitsu:libusb:001:008':
Oct 02 17:36:50 printnscan server.js[18540]:   Scan Mode:
Oct 02 17:36:50 printnscan server.js[18540]:     --source ADF Front|ADF Back|ADF Duplex [ADF Front]
Oct 02 17:36:50 printnscan server.js[18540]:         Selects the scan source (such as a document-feeder).
Oct 02 17:36:50 printnscan server.js[18540]:     --mode Lineart|Gray|Color [Lineart]
Oct 02 17:36:50 printnscan server.js[18540]:         Selects the scan mode (e.g., lineart, monochrome, or color).
Oct 02 17:36:50 printnscan server.js[18540]:     --resolution 50..600dpi (in steps of 1) [300]
Oct 02 17:36:50 printnscan server.js[18540]:         Sets the resolution of the scanned image.
Oct 02 17:36:50 printnscan server.js[18540]:   Geometry:
Oct 02 17:36:50 printnscan server.js[18540]:     -t 0..289.353mm (in steps of 0.0211639) [0]
Oct 02 17:36:50 printnscan server.js[18540]:         Top-left y position of scan area.
Oct 02 17:36:50 printnscan server.js[18540]:     --page-width 2.70898..219.428mm (in steps of 0.0211639) [215.872]
Oct 02 17:36:50 printnscan server.js[18540]:         Specifies the width of the media.  Required for automatic centering of
Oct 02 17:36:50 printnscan server.js[18540]:         sheet-fed scans.
Oct 02 17:36:50 printnscan server.js[18540]:     --page-height 0..450.707mm (in steps of 0.0211639) [292.062]
Oct 02 17:36:50 printnscan server.js[18540]:         Specifies the height of the media, 0 will auto-detect.
Oct 02 17:36:50 printnscan server.js[18540]:   Enhancement:
Oct 02 17:36:50 printnscan server.js[18540]:     --brightness -127..127 (in steps of 1) [0]
Oct 02 17:36:50 printnscan server.js[18540]:         Controls the brightness of the acquired image.
Oct 02 17:36:50 printnscan server.js[18540]:     --contrast -127..127 (in steps of 1) [0]
Oct 02 17:36:50 printnscan server.js[18540]:         Controls the contrast of the acquired image.
Oct 02 17:36:50 printnscan server.js[18540]:     --threshold 0..255 (in steps of 1) [120]
Oct 02 17:36:50 printnscan server.js[18540]:         Select minimum-brightness to get a white point
Oct 02 17:36:50 printnscan server.js[18540]:     --threshold-curve 0..127 (in steps of 1) [55]
Oct 02 17:36:50 printnscan server.js[18540]:         Dynamic threshold curve, from light to dark, normally 50-65
Oct 02 17:36:50 printnscan server.js[18540]:   Sensors:
Oct 02 17:36:50 printnscan server.js[18540]:     --scan[=(yes|no)] [no] [hardware]
Oct 02 17:36:50 printnscan server.js[18540]:         Scan button
Oct 02 17:36:50 printnscan server.js[18540]:     --page-loaded[=(yes|no)] [yes] [hardware]
Oct 02 17:36:50 printnscan server.js[18540]:         Page loaded
Oct 02 17:36:50 printnscan server.js[18540]:     --top-edge[=(yes|no)] [no] [hardware]
Oct 02 17:36:50 printnscan server.js[18540]:         Paper is pulled partly into adf
Oct 02 17:36:50 printnscan server.js[18540]:     --cover-open[=(yes|no)] [no] [hardware]
Oct 02 17:36:50 printnscan server.js[18540]:         Cover open
Oct 02 17:36:50 printnscan server.js[18540]:     --power-save[=(yes|no)] [yes] [hardware]
Oct 02 17:36:50 printnscan server.js[18540]:         Scanner in power saving mode
Oct 02 17:36:50 printnscan server.js[18540]: [2021-10-02T22:36:50.773Z] ERROR (Devices): Ignoring net:scanner.lan.greenrobin.net:epjitsu:libusb:001:008. Error: -l is missing from device
Oct 02 17:36:50 printnscan server.js[18540]: [2021-10-02T22:36:50.800Z] DEBUG (Http): request:  { method: 'POST', path: '/preview' }
Oct 02 17:36:50 printnscan server.js[18540]: [2021-10-02T22:36:50.801Z] DEBUG (Devices): devices.json contains no devices. Reloading
Oct 02 17:36:50 printnscan server.js[18540]: [2021-10-02T22:36:50.801Z] DEBUG (Devices): Config.devices:  []

```

**Comment by coolnovember** [comment]
ok, I think i know the problem, the installer is doing something weird when running the staging version.

After cloning the staging branch,  i had wrongly ran the installer with -a , which pulled the master branch into /var/www/scanservjs/server/
Notice that the date has the last release date Aug-28

```
mex@printnscan:/var/www/scanservjs/server$ ll
total 108
drwxr-xr-x 2 root root 4096 Oct  2 17:18 ./
drwxr-xr-x 7 root root 4096 Oct  2 17:18 ../
-rw-r--r-- 1 root root 4068 Aug 28 10:21 api.js
-rw-r--r-- 1 root root  997 Aug 28 10:21 command-builder.js
-rw-r--r-- 1 root root 8782 Aug 28 10:21 config.js
-rw-r--r-- 1 root root 4846 Aug 28 10:21 configure.js
-rw-r--r-- 1 root root  220 Aug 28 10:21 constants.js
...

```

So, I stopped the service, uninstalled it, and then manually nuked the var/www/ folder.
then looked carefully at the installer and ran it again with the -i option

That made things better in terms of putting the local copy. 
But the structure is different from what my local branch that I checked out has

The local version has
```
mex@printnscan:~/scanservjs-dev/scanservjs$ tree -L 3
.
|-- Dockerfile
|-- LICENSE
|-- README.md
|-- docs
|   |-- config.md
|   |-- development.md
|   |-- docker.md
|   |-- install.md
|   |-- integration.md
|   |-- proxy.md
|   |-- sane.md
|   |-- screen0.jpg
|   `-- troubleshooting.md
|-- package-lock.json
|-- package.json
|-- packages
|   |-- client
|   |   |-- babel.config.js
|   |   |-- jsconfig.json
|   |   |-- package-lock.json
|   |   |-- package.json
|   |   |-- src
|   |   `-- vue.config.js
|   `-- server
|       |-- config
|       |-- data
|       |-- gulpfile.js
|       |-- installer.sh
|       |-- package-lock.json
|       |-- package.json
|       |-- scanservjs.service
|       |-- src
|       `-- test
|-- run.sh
`-- vetur.config.js


```
Whereas the  /var/www/scanservjs/ has a very different set of files

```
mex@printnscan:/var/www/scanservjs$ ll
total 576
drwxr-xr-x  7 root       root    4096 Oct  2 17:46 ./
drwxr-xr-x  3 root       root    4096 Oct  2 17:46 ../
drwxr-xr-x  2 scanservjs users   4096 Oct  2 17:16 config/
drwxr-xr-x  5 scanservjs users   4096 Sep  1 07:32 data/
-rw-r--r--  1 root       root    2037 Oct  2 17:46 gulpfile.js
-rwxr-xr-x  1 root       root    6168 Oct  2 17:46 installer.sh*
drwxr-xr-x 70 root       root   20480 Oct  2 17:46 node_modules/
-rw-r--r--  1 root       root  517340 Oct  2 17:46 package-lock.json
-rw-r--r--  1 root       root    1065 Oct  2 17:46 package.json
-rw-r--r--  1 root       root     304 Oct  2 17:46 scanservjs.service
drwxr-xr-x  2 root       root    4096 Oct  2 17:46 src/
drwxr-xr-x  3 root       root    4096 Oct  2 17:46 test/

```

The actual service now fails with 

Oct 02 17:47:41 printnscan systemd[1]: Stopped scanservjs.
Oct 02 17:47:41 printnscan systemd[1]: Started scanservjs.
Oct 02 17:47:41 printnscan systemd[19373]: scanservjs.service: Failed to execute command: No such file or directory
Oct 02 17:47:41 printnscan systemd[19373]: scanservjs.service: Failed at step EXEC spawning /var/www/scanservjs/server/server.js: No such file or directory
Oct 02 17:47:41 printnscan systemd[1]: scanservjs.service: Main process exited, code=exited, status=203/EXEC
Oct 02 17:47:41 printnscan systemd[1]: scanservjs.service: Failed with result 'exit-code'.
Oct 02 17:47:41 printnscan systemd[1]: scanservjs.service: Scheduled restart job, restart counter is at 5.
Oct 02 17:47:41 printnscan systemd[1]: Stopped scanservjs.
Oct 02 17:47:41 printnscan systemd[1]: scanservjs.service: Start request repeated too quickly.
Oct 02 17:47:41 printnscan systemd[1]: scanservjs.service: Failed with result 'exit-code'.
Oct 02 17:47:41 printnscan systemd[1]: Failed to start scanservjs.
```

which makes sense, there is no path /var/www/scanservjs/server/  The folder that the installer copied has something very different in it. Looks more like source code than the built versions

**Comment by coolnovember** [comment]
... and this was totally completely user error. 
I forgot to build it! :(
I ran build and then dev run via your instructions here https://github.com/sbs20/scanservjs/blob/master/docs/development.md() and it worked beautifully!

**Comment by sbs20** [comment]
> Sorry for all of the spam

Haha - no worries. I'm glad it worked. I think I need to make it clearer that the install script only works for master.
