### ISSUE TITLE
The app can't find my scanner. HP DeskJet 2130 [solved]

### ISSUE THREAD

**Issue by sebPomme** [sbs20/scanservjs#355]
Hi, thanks for this project and I hope we can make it works with my setup.
**Describe the bug**
The app can't find my scanner. 

**To Reproduce**
1. Go to 'the main page'
2. Click on 'nothing'
3. See error

**Expected behavior**
Scan from the web interface.

**Screenshots**
![device](https://user-images.githubusercontent.com/4944971/133131420-aca61e79-45b6-4d34-ab9d-cd72960801e3.png)

**Client (please complete the following information):**
 - Opera
 - Version :78.0.4093.184 

**Server (please complete the following information):**
 - OS: Raspbian GNU/Linux 11 (bullseye)
 - Docker version : 20.10.8

**Logs**
 ```
engine_1  | node ./server/server.js
engine_1  | + node ./server/server.js
engine_1  | [2021-09-13T17:21:43.445Z] INFO (server): Started
engine_1  | [2021-09-13T17:23:22.316Z] DEBUG (Http): request:  { method: 'GET', path: '/context' }
engine_1  | [2021-09-13T17:23:22.344Z] DEBUG (Devices): devices.json does not exist. Reloading
engine_1  | [2021-09-13T17:23:22.345Z] DEBUG (Devices): Config.devices:  []
engine_1  | [2021-09-13T17:23:26.900Z] DEBUG (Devices): Device list:
engine_1  | No scanners were identified. If you were expecting something different,
engine_1  | check that the scanner is plugged in, turned on and detected by the
engine_1  | sane-find-scanner tool (if appropriate). Please read the documentation
engine_1  | which came with this software (README, FAQ, manpages).
engine_1  |
engine_1  | [2021-09-13T17:23:26.963Z] DEBUG (Http): request:  { method: 'POST', path: '/preview' }
engine_1  | [2021-09-13T17:23:26.970Z] DEBUG (Devices): devices.json contains no devices. Reloading
engine_1  | [2021-09-13T17:23:26.970Z] DEBUG (Devices): Config.devices:  []
engine_1  | [2021-09-13T17:23:31.477Z] DEBUG (Devices): Device list:
engine_1  | No scanners were identified. If you were expecting something different,
engine_1  | check that the scanner is plugged in, turned on and detected by the
engine_1  | sane-find-scanner tool (if appropriate). Please read the documentation
engine_1  | which came with this software (README, FAQ, manpages).
engine_1  |
```

This may be useful
```sh
# Node version
scanservjs@scanservjs-docker:/app$ echo "node: $(node -v)"
node: v14.17.6

# NPM version
scanservjs@scanservjs-docker:/app$ echo "npm: $(npm -v)"
npm: 7.11.2

# Docker version
pomme@rpi-4:~ $ echo "docker: $(docker -v)"
docker: Docker version 20.10.8, build 3967b7d

# OS version
pomme@rpi-4:~ $ cat /etc/*release | sed ':a;N;$!ba;s/\n/; /g'
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"; NAME="Raspbian GNU/Linux"; VERSION_ID="11"; VERSION="11 (bullseye)"; VERSION_CODENAME=bullseye; ID=raspbian; ID_LIKE=debian; HOME_URL="http://www.raspbian.org/"; SUPPORT_URL="http://www.raspbian.org/RaspbianForums"; BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

**Additional context**
Trying the command inside the container as scanservjs
```sh
pomme@rpi-4:~ $ docker exec -t -i scanservjs_engine_1 scanimage -L

No scanners were identified. If you were expecting something different,
check that the scanner is plugged in, turned on and detected by the
sane-find-scanner tool (if appropriate). Please read the documentation
which came with this software (README, FAQ, manpages).

```
Same result as root in the container.

No more luck with sane-find-scanner
```
pomme@rpi-4:~ $ docker exec -t -i scanservjs_engine_1 sane-find-scanner

  # bla bla bla commented content
could not open USB device 0x174c/0x55aa at 002:002: Access denied (insufficient permissions)
could not open USB device 0x1d6b/0x0003 at 002:001: Access denied (insufficient permissions)
could not open USB device 0x10c4/0xea60 at 001:004: Access denied (insufficient permissions)
could not open USB device 0x03f0/0xe111 at 001:011: Access denied (insufficient permissions)
could not open USB device 0x2109/0x3431 at 001:002: Access denied (insufficient permissions)
could not open USB device 0x1d6b/0x0002 at 001:001: Access denied (insufficient permissions)
  # bla bla bla
```
But as root it's kinda works 
```
pomme@rpi-4:~ $ docker exec -t -i -u root scanservjs_engine_1 sane-find-scanner

  # sane-find-scanner will now attempt to detect your scanner. If the
  # result is different from what you expected, first make sure your
  # scanner is powered up and properly connected to your computer.

  # No SCSI scanners found. If you expected something different, make sure that
  # you have loaded a kernel SCSI driver for your SCSI adapter.

found USB scanner (vendor=0x03f0 [HP], product=0xe111 [DeskJet 2130 series]) at libusb:001:011
could not fetch string descriptor: Pipe error
  # Your USB scanner was (probably) detected. It may or may not be supported by
  # SANE. Try scanimage -L and read the backend's manpage.

  # Not checking for parallel port scanners.

  # Most Scanners connected to the parallel port or other proprietary ports
  # can't be detected by this program.

```

Do you have and idea where I can look next ?

Pomme :apple:

**Comment by sbs20** [comment]
Are you running the standard docker image on a raspberry pi? If so, it's an amd64 image and won't run on ARM. The easiest way on a pi is just to install using the one line install under "manual install"

**Comment by sebPomme** [comment]
I manage to get it works by install new sane-backend (hplip), but
```
pomme@rpi-4:~ $ docker exec -t -i -u root scanservjs_engine_1 apt update
Hit:1 http://deb.debian.org/debian buster InRelease
Get:2 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]
Get:3 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
Hit:4 http://download.opensuse.org/repositories/home:/pzz/Debian_10  InRelease
Fetched 117 kB in 2s (72.4 kB/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
pomme@rpi-4:~ $ docker exec -t -i -u root scanservjs_engine_1 apt install hplip -yq
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
# BLABLABLA
```
And, it's works at root:
```
pomme@rpi-4:~ $ docker exec -t -i -u root scanservjs_engine_1 scanimage -L
device `hpaio:/usb/DeskJet_2130_series?serial=CN5A8393M0067S' is a Hewlett-Packard DeskJet_2130_series all-in-one
```
But not as scanservjs user:
```
pomme@rpi-4:~ $ docker exec -t -i scanservjs_engine_1 scanimage -L
dbus[25]: arguments to dbus_connection_send() were incorrect, assertion "connection != NULL" failed in file ../../../dbus/dbus-connection.c line 3307.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
```

And I have a new error message
```
[2021-09-13T18:23:57.660Z] ERROR (Http): Error: Command failed: /usr/bin/scanimage -L
dbus[37]: arguments to dbus_connection_send() were incorrect, assertion "connection != NULL" failed in file ../../../dbus/dbus-connection.c line 3307.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
Aborted

    at ChildProcess.exithandler (child_process.js:390:12)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
  killed: false,
  code: 134,
  signal: null,
  cmd: '/usr/bin/scanimage -L',
  stdout: '',
  stderr: 'dbus[37]: arguments to dbus_connection_send() were incorrect, assertion "connection != NULL" failed in file ../../../dbus/dbus-connection.c line 3307.\n' +
    'This is normally a bug in some application using the D-Bus library.\n' +
    '\n' +
    '  D-Bus not built with -rdynamic so unable to print a backtrace\n' +
    'Aborted\n'
}
[2021-09-13T18:23:57.713Z] DEBUG (Http): request:  { method: 'POST', path: '/preview' }
[2021-09-13T18:23:57.717Z] DEBUG (Devices): devices.json contains no devices. Reloading
[2021-09-13T18:23:57.718Z] DEBUG (Devices): Config.devices:  []
```
![device_000](https://user-images.githubusercontent.com/4944971/133137396-1dad29c6-d236-44b3-884f-a00b17b9a3bd.png)

**Comment by sebPomme** [comment]
> Are you running the standard docker image on a raspberry pi? If so, it's an amd64 image and won't run on ARM. The easiest way on a pi is just to install using the one line install under "manual install"

No, I build it directly from this repository.
Ok I will get an another raspberry pi and try the manual install, cause the dependence are too hi.

**Comment by sebPomme** [comment]
By default it's fail outside docker too with my scanner.
```
{
  "os": {
    "arch": "arm",
    "freemem": 149,
    "platform": "linux",
    "release": "5.10.60-v7+",
    "type": "Linux",
    "version": "#1449 SMP Wed Aug 25 15:00:01 BST 2021"
  },
  "node": "v12.22.5",
  "npm": "7.11.2",
  "docker": false
}
```
BUT 

:heavy_check_mark: it's works, I think the package `libsane-hpaio` (dependency of hplip) is really usefull for my `hpaio:/usb/DeskJet_2130_series?serial=CN5A8393M0067S`. :heavy_check_mark: 

So, for summary `apt install libsane-hpaio  --no-install-recommends` is the fix for the printer HP DeskJet 2130 (without docker)

Unfortunatly I can't say why it doesn't work inside the container with the same fix, cause I m not familar with dbus.

Thanks for the help & thanks for the short reply :+1: 
:apple:

**Comment by sbs20** [comment]
I don't know enough about the inner workings of linux and `dbus` - I just know that in order for driverless scanning to work dbus needs to be shared over docker (notes [here](https://github.com/sbs20/scanservjs/blob/master/docs/docker.md#accessing-hardware)).

It seems there is some incompatibility somewhere in SANE with your printer. I don't know whether this is RPi specific / HP specific or SANE itself..

I'm glad you managed to get it all working though and thank you for sharing your findings.

**Comment by ety001** [comment]
I have the same issue.

I add the HP driver and rebuild an docker image. 
[https://github.com/ety001/scanservjs/commit/086d6bcc27d3458b071029fad8a885e10d1131aa](https://github.com/ety001/scanservjs/commit/086d6bcc27d3458b071029fad8a885e10d1131aa)

Then run the docker image as root permission.
```
docker run -itd \
  -p 8080:8080 \
  -v /var/run/dbus:/var/run/dbus \
  -v /data/files/scanner:/app/data/output \
  --device=/dev/bus/usb/009/002:/dev/bus/usb/009/002 \
  -u root \
  --restart always \
  --name scanner \
  --privileged \
  ety001/scanner:latest
```

Now the issue was fixed.
