### ISSUE TITLE
cache resources exhausted

### ISSUE THREAD

**Issue by ziyatdinov** [sbs20/scanservjs#356]
**Describe the bug**
Scan > 600 

# Node version
node: v14.17.5

# NPM version
npm: 7.11.2

# Docker version
docker: Docker version 20.10.8, build 3967b7d

# OS version
PRETTY_NAME="Debian GNU/Linux 10 (buster)"; NAME="Debian GNU/Linux"; VERSION_ID="10"; VERSION="10 (buster)"; VERSION_CODENAME=buster; ID=debian; HOME_URL="https://www.debian.org/"; SUPPORT_URL="https://www.debian.org/support"; BUG_REPORT_URL="https://bugs.debian.org/"

# Logs if in docker
[2021-09-15T12:37:19.389Z] DEBUG (Scan): Post processing: JPG | @:pipeline.high-quality
[2021-09-15T12:37:19.390Z] DEBUG (Process): /usr/bin/convert 'data/temp/~tmp-scan-0-0001.tif' -background '#808080' -extent '10204.72440944882x14173.228346456694-0-0' -resize 868 'data/preview/preview.tif',  undefined , {"encoding":"binary","shell":true,"maxBuffer":16384,"ignoreErrors":false}

[2021-09-15T12:37:20.563Z] ERROR (Http): Error: /usr/bin/convert 'data/temp/~tmp-scan-0-0001.tif' -background '#808080' -extent '10204.72440944882x14173.228346456694-0-0' -resize 868 'data/preview/preview.tif' exited with code: 1, stderr: convert: cache resources exhausted `data/temp/~tmp-scan-0-0001.tif' @ error/cache.c/OpenPixelCache/4083.
    at ChildProcess.<anonymous> (/app/server/process.js:54:18)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Socket.<anonymous> (internal/child_process.js:441:11)
    at Socket.emit (events.js:400:28)
    at Pipe.<anonymous> (net.js:675:12)

**Comment by sbs20** [comment]
Not seen that before. Are you able to shell into the container and change `/etc/ImageMagick-6/policy.xml`

Change

```xml
<policy domain="resource" name="disk" value="1GiB"/>
```

to

```
<policy domain="resource" name="disk" value="8GiB"/>
```

if that works, I'll update the dockerfile.

See [this](https://stackoverflow.com/a/53699200)

**Comment by ziyatdinov** [comment]
Yes, good. It works.
