### ISSUE TITLE
Scanner not found

### ISSUE THREAD

**Issue by ebretteville** [sbs20/scanservjs#359]
[scanservjs.log.installed.txt.gz](https://github.com/sbs20/scanservjs/files/7213532/scanservjs.log.installed.txt.gz)
**Describe the bug**
no scanners found even if the scanner is recognized in sane

**Client (please complete the following information):**
 - firefox desktop macosx
 - latest: 93.0b8 (64 bits)

**Server (please complete the following information):**
 - OS: Linux scan-sane 5.10.60+ #1449 Wed Aug 25 14:59:20 BST 2021 armv6l GNU/Linux
 - Node version : v10.24.0
 - NPM version : 7.11.2

**Logs**
 node: v10.24.0
npm: 7.11.2
<img width="2032" alt="Capture d’écran 2021-09-22 à 21 04 42" src="https://user-images.githubusercontent.com/3687099/134405915-19c7329c-3022-414c-a420-5e0dc2480bd7.png">

```
pi@scan-sane:~ $ scanimage -L
device `epjitsu:libusb:001:002' is a FUJITSU ScanSnap S1300i scanner
```
```
pi@scan-sane:~ $ sane-find-scanner -q
found USB scanner (vendor=0x04c5 [FUJITSU], product=0x128d [ScanSnap S1300i]) at libusb:001:002
could not open USB device 0x1d6b/0x0002 at 001:001: Access denied (insufficient permissions)
```
```
pi@scan-sane:~ $ more /etc/udev/rules.d/55-libsane.rules
ATTRS{idVendor}=="04c5", ATTRS{idProduct}=="128d", MODE="0666", GROUP="scanner", ENV{libsane_matched}="yes"
```
```
pi@scan-sane:~ $ lsusb
Bus 001 Device 002: ID 04c5:128d Fujitsu, Ltd
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```
```
pi@scan-sane:~ $ grep scanner  /etc/group
scanner:x:114:saned,scanservjs,pi,httpdusr,www-data,root
```

PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"; NAME="Raspbian GNU/Linux"; VERSION_ID="10"; VERSION="10 (buster)"; VERSION_CODENAME=buster; ID=raspbian; ID_LIKE=debian; HOME_URL="http://www.raspbian.org/"; SUPPORT_URL="http://www.raspbian.org/RaspbianForums"; BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Comment by sbs20** [comment]
Could you include the logs too please:

```
sudo journalctl -u scanservjs | gzip > scanservjs.log.installed.txt.gz
```

And upload the gzip here.

**Comment by ebretteville** [comment]
done

**Comment by sbs20** [comment]
Thank you. I've managed to look, and I'm sorry for the hassle (I'm away and on my phone) - but this is actually #350 after all.

You can either attempt to build yourself (clone the dev branch and build) or wait for me to promote it which will take a week or two.

I'm going to close this issue and leave the other open.

**Comment by ebretteville** [comment]
i know how to git clone but not sure about the build commands involved... If you can help, I can be a beta test

**Comment by sbs20** [comment]
Try this: https://github.com/sbs20/scanservjs/blob/master/docs/development.md#install-and-setup

But after the clone you'll need to switch branch and pull.

**Comment by ebretteville** [comment]
Tried to build 2.71.2, stucked two times at 66% header.js... Will try another time but it's quite slow on a raspberry pi zero

**Comment by ebretteville** [comment]
```
pi@scan-sane:~ $ cd scanservjs/
pi@scan-sane:~/scanservjs $ git pull
Déjà à jour.
pi@scan-sane:~/scanservjs $ npm run serve

> scanservjs@2.17.2 serve
> cd packages/client && npm run serve


> scanservjs@2.17.2 serve
> nodemon --exec 'vue-cli-service serve'

[nodemon] 2.0.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): ../server/src/**/*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `vue-cli-service serve`
 INFO  Starting development server...
66% building 750/803 modules 53 active /home/pi/scanservjs/packages/client/node_modules/vuetify/lib/components/VDataTable/mixins/header.js
```

**Comment by ebretteville** [comment]
+1

**Comment by sbs20** [comment]
I just tried this on a pi4 and it worked (though was very slow).

The only thing I can suggest is trying to do a build instead (`npm run build`) which will create a build under `./dist` then run the build instead.

```
npm run build
cd dist
npm i .
node server/server.js
```

But I suspect the build will just take forever.

**Comment by ebretteville** [comment]
```
pi@scan-sane:~/scanservjs $ npm run build

> scanservjs@2.17.2 build
> npm run clean && cd packages/client && npm run build && cd ../server && npm run build


> scanservjs@2.17.2 clean
> rm -rf ./dist


> scanservjs@2.17.2 build
> vue-cli-service build


⠼  Building for production...

 WARNING  Compiled with 3 warnings                                                                                                                                                     20:25:41

 warning

asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  fonts/materialdesignicons-webfont.7a44ea19.woff2 (318 KiB)
  fonts/materialdesignicons-webfont.147e3378.woff (454 KiB)
  fonts/materialdesignicons-webfont.64d4cf64.eot (1000 KiB)
  fonts/materialdesignicons-webfont.174c02fc.ttf (1000 KiB)
  css/chunk-vendors.6a023528.css (686 KiB)
  js/chunk-vendors.9c06a908.js (553 KiB)

 warning

entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  index (1.3 MiB)
      css/chunk-vendors.6a023528.css
      js/chunk-vendors.9c06a908.js
      css/index.b2715776.css
      js/index.9eda1d2a.js


 warning

webpack performance recommendations:
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/

  File                                                Size                                                               Gzipped

  ../../dist/client/js/chunk-vendors.9c06a908.js      552.81 KiB                                                         173.44 KiB
  ../../dist/client/js/index.9eda1d2a.js              93.43 KiB                                                          26.14 KiB
  ../../dist/client/css/chunk-vendors.6a023528.css    685.82 KiB                                                         93.34 KiB
  ../../dist/client/css/index.b2715776.css            0.47 KiB                                                           0.26 KiB

  Images and other types of assets omitted.

 DONE  Build complete. The ../../dist/client directory is ready to be deployed.
 INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html


> scanservjs-server@2.17.2 build
> gulp build

[20:27:03] Using gulpfile ~/scanservjs/packages/server/gulpfile.js
[20:27:03] Starting 'build'...
[20:27:07] Finished 'build' after 3.65 s
pi@scan-sane:~/scanservjs $ ls
dist  Dockerfile  docs  LICENSE  package.json  package-lock.json  packages  README.md  run.sh  vetur.config.js
pi@scan-sane:~/scanservjs $ cd d
dist/ docs/
pi@scan-sane:~/scanservjs $ cd dist/
pi@scan-sane:~/scanservjs/dist $ npm i .
npm WARN EBADENGINE Unsupported engine { package: 'gulp-filter@7.0.0',
npm WARN EBADENGINE   required: { node: '>=12' },
npm WARN EBADENGINE   current: { node: 'v10.24.0', npm: '7.11.2' } }

added 712 packages, and audited 713 packages in 4m

10 vulnerabilities (4 low, 6 moderate)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
pi@scan-sane:~/scanservjs/dist $ node server/server.js
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::8080
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Function.listen (/home/pi/scanservjs/dist/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/pi/scanservjs/dist/server/server.js:13:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
Emitted 'error' event at:
    at emitErrorNT (net.js:1307:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

**Comment by sbs20** [comment]
> Error: listen EADDRINUSE: address already

Something else is already running on port 8080. Possibly scanservjs. Stop whatever else is doing it and try that last line again. Or you can change the config to use another port like 8081

**Comment by ebretteville** [comment]
Oh I see I first tried to install scanserv the php version, i'm going to look to uninstall it

**Comment by ebretteville** [comment]
it keeps restarting

```
pi@scan-sane:~/scanservjs/dist $ node server/server.js
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::8080
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Function.listen (/home/pi/scanservjs/dist/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/pi/scanservjs/dist/server/server.js:13:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
Emitted 'error' event at:
    at emitErrorNT (net.js:1307:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
pi@scan-sane:~/scanservjs/dist $  sudo netstat -tulpn | grep LISTEN
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      441/sshd
tcp6       0      0 :::8080                 :::*                    LISTEN      29759/node
tcp6       0      0 :::22                   :::*                    LISTEN      441/sshd
pi@scan-sane:~/scanservjs/dist $
```

I deleted the scanserv folder from /var/www/html and killed the processes but without any luck

**Comment by sbs20** [comment]
It looks like node is bound to 8080, not php.

Try `ps ax | grep 29759` - that should reveal the culprit. Could it be scanservjs? If so, `sudo systemctl stop scanservjs`.

**Comment by ebretteville** [comment]
it was scanservjs, but after killing it, git pull, the commands in https://github.com/sbs20/scanservjs/issues/359#issuecomment-930315921, the scanner was recognized I had other errors in https://github.com/sbs20/scanservjs/issues/350#issuecomment-930274591, will follow this other issues.

**Comment by sbs20** [comment]
Maybe pull the development branch again.

**Comment by ebretteville** [comment]
I did it before my comments... STrange, will try it again.

**Comment by sbs20** [comment]
And don't forget to rebuild!

**Comment by ebretteville** [comment]
I will:
```
cd scanservjs
git pull
npm run build
cd dist
npm i .
node server/server.js
```
