### ISSUE TITLE
Allow to cut off borders

### ISSUE THREAD

**Issue by CubicrootXYZ** [sbs20/scanservjs#575]
**Describe the bug**

I am using a ScanSnap 1300i. There is no size selection and the scans are always in 219x292 what should be 208x292 (at least the ScanSnap application scans with that size). This results in ugly grey stripes on the left and right side of the scan. 

**To Reproduce**
1. Scan a file with the ScanSnap 1300i
2. Observer thick gray borders

**Expected behavior**

Some setting to cut off those borders/specify the correct size.

**Screenshots**

![image](https://user-images.githubusercontent.com/24812442/222972575-2be24893-7ee0-48a4-b564-0e9d5faa2d4b.png)

**Client (please complete the following information):**
 - Browser: Firefox 110.0.1
 - Version: v2.26.0

**Server (please complete the following information):**
 - OS: Ubuntu 22.04
 - Docker: 23.0.1

Running the docker official docker image with `latest` tag.

**Logs**
 - Please include application logs (see commands below)
```
[2023-03-05T16:23:46.613Z] INFO (Http): { method: 'GET', path: '/preview' }
[2023-03-05T16:23:46.657Z] INFO (Process): { spawn: 'convert - -quality 75 jpg:-' }
[2023-03-05T16:23:50.574Z] INFO (Http): {
  method: 'POST',
  path: '/scan',
  body: {
    version: '2.26.0',
    params: {
      deviceId: 'epjitsu:libusb:001:006',
      resolution: 300,
      top: 0,
      pageHeight: 292,
      pageWidth: 215.8,
      mode: 'Color',
      source: 'ADF Front',
      brightness: 60,
      contrast: 85
    },
    filters: [],
    pipeline: 'PDF with OCR (OCRMYPDF | @:pipeline.high-quality)',
    batch: 'auto',
    index: 1
  }
}
[2023-03-05T16:23:50.583Z] INFO (ScanController): Scanning
[2023-03-05T16:23:50.585Z] INFO (Process): {
  spawn: "/usr/bin/scanimage -d epjitsu:libusb:001:006 --mode Color --source 'ADF Front' --resolution 300 --page-width 215.8 --page-height 292 -t 0 --format tiff --brightness 60 --contrast 85 --batch=data/temp/~tmp-scan-1-%04d.tif"
}
[2023-03-05T16:24:58.857Z] INFO (Process): {
  spawn: '/usr/bin/convert data/temp/~tmp-scan-1-0001.tif -scale 868 data/preview/preview.tif'
}
[2023-03-05T16:24:59.475Z] INFO (Process): { spawn: 'convert @- -quality 92 tmp-%04d.jpg && ls tmp-*.jpg' }
[2023-03-05T16:25:06.350Z] INFO (Process): { spawn: 'convert @- pdf:-' }
[2023-03-05T16:25:20.913Z] INFO (Process): {
  spawn: 'ocrmypdf -l eng --deskew --rotate-pages --rotate-pages-threshold 1.8 --optimize 2 --force-ocr - scan_0000.pdf'
}
[2023-03-05T16:27:26.856Z] INFO (Process): { spawn: 'ls scan_*.*' }
[2023-03-05T16:27:26.981Z] ERROR (Http): ReferenceError: Process is not defined
    at Object.afterScan (/app/config/config.local.js:73:5)
    at UserOptions.afterScan (/app/server/classes/user-options.js:41:31)
    at ScanController.execute (/app/server/scan-controller.js:179:25)
    at async Object.run (/app/server/scan-controller.js:203:12)
    at async Api.scan (/app/server/api.js:140:12)
    at async /app/server/configure.js:246:16
[2023-03-05T16:27:35.571Z] INFO (Http): { method: 'GET', path: '/files' }
[2023-03-05T16:27:35.572Z] INFO (Http): { method: 'GET', path: '/context' }
[2023-03-05T16:27:35.585Z] INFO (Api): Context {
  devices: [
    Device {
      id: 'epjitsu:libusb:001:006',
      name: 'epjitsu:libusb:001:006',
      features: {
        '--source': Feature {
          text: '--source ADF Front|ADF Back|ADF Duplex [ADF Front]',
          name: '--source',
          default: 'ADF Front',
          parameters: 'ADF Front|ADF Back|ADF Duplex',
          meta: undefined,
          enabled: true,
          options: [ 'ADF Front', 'ADF Back', 'ADF Duplex' ]
        },
        '--mode': Feature {
          text: '--mode Lineart|Gray|Color [Lineart]',
          name: '--mode',
          default: 'Lineart',
          parameters: 'Lineart|Gray|Color',
          meta: undefined,
          enabled: true,
          options: [ 'Lineart', 'Gray', 'Color' ]
        },
        '--resolution': Feature {
          text: '--resolution 50..600dpi (in steps of 1) [300]',
          name: '--resolution',
          default: 300,
          parameters: '50..600dpi (in steps of 1)',
          meta: undefined,
          enabled: true,
          limits: [ 50, 600 ],
          interval: 1,
          options: [ 50, 75, 150, 300, 600 ]
        },
        '-t': Feature {
          text: '-t 0..289.353mm (in steps of 0.0211639) [0]',
          name: '-t',
          default: 0,
          parameters: '0..289.353mm (in steps of 0.0211639)',
          meta: undefined,
          enabled: true,
          limits: [ 0, 289.3 ],
          interval: 0.0211639
        },
        '--page-width': Feature {
          text: '--page-width 2.70898..219.428mm (in steps of 0.0211639) [215.872]',
          name: '--page-width',
          default: 215.8,
          parameters: '2.70898..219.428mm (in steps of 0.0211639)',
          meta: undefined,
          enabled: true,
          limits: [ 2.7, 219.4 ],
          interval: 0.0211639
        },
        '--page-height': Feature {
          text: '--page-height 0..450.707mm (in steps of 0.0211639) [292.062]',
          name: '--page-height',
          default: 292,
          parameters: '0..450.707mm (in steps of 0.0211639)',
          meta: undefined,
          enabled: true,
          limits: [ 0, 450.7 ],
          interval: 0.0211639
        },
        '--brightness': Feature {
          text: '--brightness -127..127 (in steps of 1) [0]',
          name: '--brightness',
          default: 60,
          parameters: '-127..127 (in steps of 1)',
          meta: undefined,
          enabled: true,
          limits: [ -127, 127 ],
          interval: 1
        },
        '--contrast': Feature {
          text: '--contrast -127..127 (in steps of 1) [0]',
          name: '--contrast',
          default: 85,
          parameters: '-127..127 (in steps of 1)',
          meta: undefined,
          enabled: true,
          limits: [ -127, 127 ],
          interval: 1
        },
        '--threshold': Feature {
          text: '--threshold 0..255 (in steps of 1) [120]',
          name: '--threshold',
          default: '120',
          parameters: '0..255 (in steps of 1)',
          meta: undefined,
          enabled: true
        },
        '--threshold-curve': Feature {
          text: '--threshold-curve 0..127 (in steps of 1) [55]',
          name: '--threshold-curve',
          default: '55',
          parameters: '0..127 (in steps of 1)',
          meta: undefined,
          enabled: true
        },
        '--scan': Feature {
          text: '--scan[=(yes|no)] [no] [hardware]',
          name: '--scan',
          default: 'no',
          parameters: '[=(yes|no)]',
          meta: 'hardware',
          enabled: true
        },
        '--page-loaded': Feature {
          text: '--page-loaded[=(yes|no)] [yes] [hardware]',
          name: '--page-loaded',
          default: 'yes',
          parameters: '[=(yes|no)]',
          meta: 'hardware',
          enabled: true
        },
        '--top-edge': Feature {
          text: '--top-edge[=(yes|no)] [yes] [hardware]',
          name: '--top-edge',
          default: 'yes',
          parameters: '[=(yes|no)]',
          meta: 'hardware',
          enabled: true
        },
        '--cover-open': Feature {
          text: '--cover-open[=(yes|no)] [no] [hardware]',
          name: '--cover-open',
          default: 'no',
          parameters: '[=(yes|no)]',
          meta: 'hardware',
          enabled: true
        },
        '--power-save': Feature {
          text: '--power-save[=(yes|no)] [yes] [hardware]',
          name: '--power-save',
          default: 'yes',
          parameters: '[=(yes|no)]',
          meta: 'hardware',
          enabled: true
        }
      },
      string: '\n' +
        "All options specific to device `epjitsu:libusb:001:006':\n" +
        '  Scan Mode:\n' +
        '    --source ADF Front|ADF Back|ADF Duplex [ADF Front]\n' +
        '        Selects the scan source (such as a document-feeder).\n' +
        '    --mode Lineart|Gray|Color [Lineart]\n' +
        '        Selects the scan mode (e.g., lineart, monochrome, or color).\n' +
        '    --resolution 50..600dpi (in steps of 1) [300]\n' +
        '        Sets the resolution of the scanned image.\n' +
        '  Geometry:\n' +
        '    -t 0..289.353mm (in steps of 0.0211639) [0]\n' +
        '        Top-left y position of scan area.\n' +
        '    --page-width 2.70898..219.428mm (in steps of 0.0211639) [215.872]\n' +
        '        Specifies the width of the media.  Required for automatic centering of\n' +
        '        sheet-fed scans.\n' +
        '    --page-height 0..450.707mm (in steps of 0.0211639) [292.062]\n' +
        '        Specifies the height of the media, 0 will auto-detect.\n' +
        '  Enhancement:\n' +
        '    --brightness -127..127 (in steps of 1) [0]\n' +
        '        Controls the brightness of the acquired image.\n' +
        '    --contrast -127..127 (in steps of 1) [0]\n' +
        '        Controls the contrast of the acquired image.\n' +
        '    --threshold 0..255 (in steps of 1) [120]\n' +
        '        Select minimum-brightness to get a white point\n' +
        '    --threshold-curve 0..127 (in steps of 1) [55]\n' +
        '        Dynamic threshold curve, from light to dark, normally 50-65\n' +
        '  Sensors:\n' +
        '    --scan[=(yes|no)] [no] [hardware]\n' +
        '        Scan button\n' +
        '    --page-loaded[=(yes|no)] [yes] [hardware]\n' +
        '        Page loaded\n' +
        '    --top-edge[=(yes|no)] [yes] [hardware]\n' +
        '        Paper is pulled partly into adf\n' +
        '    --cover-open[=(yes|no)] [no] [hardware]\n' +
        '        Cover open\n' +
        '    --power-save[=(yes|no)] [yes] [hardware]\n' +
        '        Scanner in power saving mode\n' +
        '\n',
      settings: {
        batchMode: {
          options: [ 'none', 'manual', 'auto', 'auto-collate-standard' ],
          default: 'none'
        },
        filters: {
          options: [ 'filter.auto-level', 'filter.threshold', 'filter.blur' ],
          default: []
        },
        pipeline: {
          options: [
            'JPG | @:pipeline.high-quality',
            'JPG | @:pipeline.medium-quality',
            'JPG | @:pipeline.low-quality',
            'PNG',
            'TIF | @:pipeline.uncompressed',
            'TIF | @:pipeline.lzw-compressed',
            'PDF (TIF | @:pipeline.uncompressed)',
            'PDF (TIF | @:pipeline.lzw-compressed)',
            'PDF (JPG | @:pipeline.high-quality)',
            'PDF (JPG | @:pipeline.medium-quality)',
            'PDF (JPG | @:pipeline.low-quality)',
            '@:pipeline.ocr | PDF (JPG | @:pipeline.high-quality)',
            '@:pipeline.ocr | @:pipeline.text-file',
            'PDF with OCR and Unpaper (OCRMYPDF | @:pipeline.high-quality)',
            'PDF with OCR (OCRMYPDF | @:pipeline.high-quality)'
          ],
          default: 'JPG | @:pipeline.high-quality'
        }
      }
    }
  ],
  version: '2.26.0',
  diagnostics: [
    { success: true, message: 'Found /usr/bin/scanimage' },
    { success: true, message: 'Found /usr/bin/convert' }
  ],
  paperSizes: [
    {
      name: 'A3 (@:paper-size.portrait)',
      dimensions: { x: 297, y: 420 }
    },
    {
      name: 'A4 (@:paper-size.portrait)',
      dimensions: { x: 210, y: 297 }
    },
    {
      name: 'A5 (@:paper-size.portrait)',
      dimensions: { x: 148, y: 210 }
    },
    {
      name: 'A5 (@:paper-size.landscape)',
      dimensions: { x: 210, y: 148 }
    },
    {
      name: 'A6 (@:paper-size.portrait)',
      dimensions: { x: 105, y: 148 }
    },
    {
      name: 'A6 (@:paper-size.landscape)',
      dimensions: { x: 148, y: 105 }
    },
    {
      name: 'B3 (@:paper-size.portrait)',
      dimensions: { x: 353, y: 500 }
    },
    {
      name: 'B4 (@:paper-size.portrait)',
      dimensions: { x: 250, y: 353 }
    },
    {
      name: 'B5 (@:paper-size.portrait)',
      dimensions: { x: 176, y: 250 }
    },
    {
      name: 'B5 (@:paper-size.landscape)',
      dimensions: { x: 250, y: 176 }
    },
    {
      name: 'B6 (@:paper-size.portrait)',
      dimensions: { x: 125, y: 176 }
    },
    {
      name: 'B6 (@:paper-size.landscape)',
      dimensions: { x: 176, y: 125 }
    },
    {
      name: 'DIN D3 (@:paper-size.portrait)',
      dimensions: { x: 272, y: 385 }
    },
    {
      name: 'DIN D4 (@:paper-size.portrait)',
      dimensions: { x: 192, y: 272 }
    },
    {
      name: 'DIN D5 (@:paper-size.portrait)',
      dimensions: { x: 136, y: 192 }
    },
    {
      name: 'DIN D5 (@:paper-size.landscape)',
      dimensions: { x: 192, y: 136 }
    },
    {
      name: 'DIN D6 (@:paper-size.portrait)',
      dimensions: { x: 96, y: 136 }
    },
    {
      name: 'DIN D6 (@:paper-size.landscape)',
      dimensions: { x: 136, y: 96 }
    },
    {
      name: '@:paper-size.letter (@:paper-size.portrait)',
      dimensions: { x: 216, y: 279 }
    },
    {
      name: '@:paper-size.legal (@:paper-size.portrait)',
      dimensions: { x: 216, y: 356 }
    },
    {
      name: '@:paper-size.tabloid (@:paper-size.portrait)',
      dimensions: { x: 279, y: 432 }
    },
    {
      name: '@:paper-size.ledger (@:paper-size.portrait)',
      dimensions: { x: 432, y: 279 }
    },
    {
      name: '@:paper-size.junior-legal (@:paper-size.portrait)',
      dimensions: { x: 127, y: 203 }
    },
    {
      name: '@:paper-size.half-letter (@:paper-size.portrait)',
      dimensions: { x: 140, y: 216 }
    }
  ],
  actions: []
}
[2023-03-05T16:27:35.657Z] INFO (Http): {
  method: 'GET',
  path: '/files/2023-03-05_Scpmn_16-27-26.pdf/thumbnail',
  params: { '0': '2023-03-05_Scpmn_16-27-26.pdf' }
}
[2023-03-05T16:27:35.658Z] INFO (Process): {
  spawn: "convert 'data/output/2023-03-05_Scpmn_16-27-26.pdf'[0] -resize 256 -quality 75 jpg:-"
}
[2023-03-05T16:27:38.756Z] INFO (Http): {
  method: 'GET',
  path: '/files/2023-03-05_Scpmn_16-27-26.pdf',
  params: { '0': '2023-03-05_Scpmn_16-27-26.pdf' }
}
[2023-03-05T16:28:16.543Z] INFO (Http): { method: 'GET', path: '/context' }
[2023-03-05T16:28:16.554Z] INFO (Api): Context {
  devices: [
    Device {
      id: 'epjitsu:libusb:001:006',
      name: 'epjitsu:libusb:001:006',
      features: {
        '--source': Feature {
          text: '--source ADF Front|ADF Back|ADF Duplex [ADF Front]',
          name: '--source',
          default: 'ADF Front',
          parameters: 'ADF Front|ADF Back|ADF Duplex',
          meta: undefined,
          enabled: true,
          options: [ 'ADF Front', 'ADF Back', 'ADF Duplex' ]
        },
        '--mode': Feature {
          text: '--mode Lineart|Gray|Color [Lineart]',
          name: '--mode',
          default: 'Lineart',
          parameters: 'Lineart|Gray|Color',
          meta: undefined,
          enabled: true,
          options: [ 'Lineart', 'Gray', 'Color' ]
        },
        '--resolution': Feature {
          text: '--resolution 50..600dpi (in steps of 1) [300]',
          name: '--resolution',
          default: 300,
          parameters: '50..600dpi (in steps of 1)',
          meta: undefined,
          enabled: true,
          limits: [ 50, 600 ],
          interval: 1,
          options: [ 50, 75, 150, 300, 600 ]
        },
        '-t': Feature {
          text: '-t 0..289.353mm (in steps of 0.0211639) [0]',
          name: '-t',
          default: 0,
          parameters: '0..289.353mm (in steps of 0.0211639)',
          meta: undefined,
          enabled: true,
          limits: [ 0, 289.3 ],
          interval: 0.0211639
        },
        '--page-width': Feature {
          text: '--page-width 2.70898..219.428mm (in steps of 0.0211639) [215.872]',
          name: '--page-width',
          default: 215.8,
          parameters: '2.70898..219.428mm (in steps of 0.0211639)',
          meta: undefined,
          enabled: true,
          limits: [ 2.7, 219.4 ],
          interval: 0.0211639
        },
        '--page-height': Feature {
          text: '--page-height 0..450.707mm (in steps of 0.0211639) [292.062]',
          name: '--page-height',
          default: 292,
          parameters: '0..450.707mm (in steps of 0.0211639)',
          meta: undefined,
          enabled: true,
          limits: [ 0, 450.7 ],
          interval: 0.0211639
        },
        '--brightness': Feature {
          text: '--brightness -127..127 (in steps of 1) [0]',
          name: '--brightness',
          default: 60,
          parameters: '-127..127 (in steps of 1)',
          meta: undefined,
          enabled: true,
          limits: [ -127, 127 ],
          interval: 1
        },
        '--contrast': Feature {
          text: '--contrast -127..127 (in steps of 1) [0]',
          name: '--contrast',
          default: 85,
          parameters: '-127..127 (in steps of 1)',
          meta: undefined,
          enabled: true,
          limits: [ -127, 127 ],
          interval: 1
        },
        '--threshold': Feature {
          text: '--threshold 0..255 (in steps of 1) [120]',
          name: '--threshold',
          default: '120',
          parameters: '0..255 (in steps of 1)',
          meta: undefined,
          enabled: true
        },
        '--threshold-curve': Feature {
          text: '--threshold-curve 0..127 (in steps of 1) [55]',
          name: '--threshold-curve',
          default: '55',
          parameters: '0..127 (in steps of 1)',
          meta: undefined,
          enabled: true
        },
        '--scan': Feature {
          text: '--scan[=(yes|no)] [no] [hardware]',
          name: '--scan',
          default: 'no',
          parameters: '[=(yes|no)]',
          meta: 'hardware',
          enabled: true
        },
        '--page-loaded': Feature {
          text: '--page-loaded[=(yes|no)] [yes] [hardware]',
          name: '--page-loaded',
          default: 'yes',
          parameters: '[=(yes|no)]',
          meta: 'hardware',
          enabled: true
        },
        '--top-edge': Feature {
          text: '--top-edge[=(yes|no)] [yes] [hardware]',
          name: '--top-edge',
          default: 'yes',
          parameters: '[=(yes|no)]',
          meta: 'hardware',
          enabled: true
        },
        '--cover-open': Feature {
          text: '--cover-open[=(yes|no)] [no] [hardware]',
          name: '--cover-open',
          default: 'no',
          parameters: '[=(yes|no)]',
          meta: 'hardware',
          enabled: true
        },
        '--power-save': Feature {
          text: '--power-save[=(yes|no)] [yes] [hardware]',
          name: '--power-save',
          default: 'yes',
          parameters: '[=(yes|no)]',
          meta: 'hardware',
          enabled: true
        }
      },
      string: '\n' +
        "All options specific to device `epjitsu:libusb:001:006':\n" +
        '  Scan Mode:\n' +
        '    --source ADF Front|ADF Back|ADF Duplex [ADF Front]\n' +
        '        Selects the scan source (such as a document-feeder).\n' +
        '    --mode Lineart|Gray|Color [Lineart]\n' +
        '        Selects the scan mode (e.g., lineart, monochrome, or color).\n' +
        '    --resolution 50..600dpi (in steps of 1) [300]\n' +
        '        Sets the resolution of the scanned image.\n' +
        '  Geometry:\n' +
        '    -t 0..289.353mm (in steps of 0.0211639) [0]\n' +
        '        Top-left y position of scan area.\n' +
        '    --page-width 2.70898..219.428mm (in steps of 0.0211639) [215.872]\n' +
        '        Specifies the width of the media.  Required for automatic centering of\n' +
        '        sheet-fed scans.\n' +
        '    --page-height 0..450.707mm (in steps of 0.0211639) [292.062]\n' +
        '        Specifies the height of the media, 0 will auto-detect.\n' +
        '  Enhancement:\n' +
        '    --brightness -127..127 (in steps of 1) [0]\n' +
        '        Controls the brightness of the acquired image.\n' +
        '    --contrast -127..127 (in steps of 1) [0]\n' +
        '        Controls the contrast of the acquired image.\n' +
        '    --threshold 0..255 (in steps of 1) [120]\n' +
        '        Select minimum-brightness to get a white point\n' +
        '    --threshold-curve 0..127 (in steps of 1) [55]\n' +
        '        Dynamic threshold curve, from light to dark, normally 50-65\n' +
        '  Sensors:\n' +
        '    --scan[=(yes|no)] [no] [hardware]\n' +
        '        Scan button\n' +
        '    --page-loaded[=(yes|no)] [yes] [hardware]\n' +
        '        Page loaded\n' +
        '    --top-edge[=(yes|no)] [yes] [hardware]\n' +
        '        Paper is pulled partly into adf\n' +
        '    --cover-open[=(yes|no)] [no] [hardware]\n' +
        '        Cover open\n' +
        '    --power-save[=(yes|no)] [yes] [hardware]\n' +
        '        Scanner in power saving mode\n' +
        '\n',
      settings: {
        batchMode: {
          options: [ 'none', 'manual', 'auto', 'auto-collate-standard' ],
          default: 'none'
        },
        filters: {
          options: [ 'filter.auto-level', 'filter.threshold', 'filter.blur' ],
          default: []
        },
        pipeline: {
          options: [
            'JPG | @:pipeline.high-quality',
            'JPG | @:pipeline.medium-quality',
            'JPG | @:pipeline.low-quality',
            'PNG',
            'TIF | @:pipeline.uncompressed',
            'TIF | @:pipeline.lzw-compressed',
            'PDF (TIF | @:pipeline.uncompressed)',
            'PDF (TIF | @:pipeline.lzw-compressed)',
            'PDF (JPG | @:pipeline.high-quality)',
            'PDF (JPG | @:pipeline.medium-quality)',
            'PDF (JPG | @:pipeline.low-quality)',
            '@:pipeline.ocr | PDF (JPG | @:pipeline.high-quality)',
            '@:pipeline.ocr | @:pipeline.text-file',
            'PDF with OCR and Unpaper (OCRMYPDF | @:pipeline.high-quality)',
            'PDF with OCR (OCRMYPDF | @:pipeline.high-quality)'
          ],
          default: 'JPG | @:pipeline.high-quality'
        }
      }
    }
  ],
  version: '2.26.0',
  diagnostics: [
    { success: true, message: 'Found /usr/bin/scanimage' },
    { success: true, message: 'Found /usr/bin/convert' }
  ],
  paperSizes: [
    {
      name: 'A3 (@:paper-size.portrait)',
      dimensions: { x: 297, y: 420 }
    },
    {
      name: 'A4 (@:paper-size.portrait)',
      dimensions: { x: 210, y: 297 }
    },
    {
      name: 'A5 (@:paper-size.portrait)',
      dimensions: { x: 148, y: 210 }
    },
    {
      name: 'A5 (@:paper-size.landscape)',
      dimensions: { x: 210, y: 148 }
    },
    {
      name: 'A6 (@:paper-size.portrait)',
      dimensions: { x: 105, y: 148 }
    },
    {
      name: 'A6 (@:paper-size.landscape)',
      dimensions: { x: 148, y: 105 }
    },
    {
      name: 'B3 (@:paper-size.portrait)',
      dimensions: { x: 353, y: 500 }
    },
    {
      name: 'B4 (@:paper-size.portrait)',
      dimensions: { x: 250, y: 353 }
    },
    {
      name: 'B5 (@:paper-size.portrait)',
      dimensions: { x: 176, y: 250 }
    },
    {
      name: 'B5 (@:paper-size.landscape)',
      dimensions: { x: 250, y: 176 }
    },
    {
      name: 'B6 (@:paper-size.portrait)',
      dimensions: { x: 125, y: 176 }
    },
    {
      name: 'B6 (@:paper-size.landscape)',
      dimensions: { x: 176, y: 125 }
    },
    {
      name: 'DIN D3 (@:paper-size.portrait)',
      dimensions: { x: 272, y: 385 }
    },
    {
      name: 'DIN D4 (@:paper-size.portrait)',
      dimensions: { x: 192, y: 272 }
    },
    {
      name: 'DIN D5 (@:paper-size.portrait)',
      dimensions: { x: 136, y: 192 }
    },
    {
      name: 'DIN D5 (@:paper-size.landscape)',
      dimensions: { x: 192, y: 136 }
    },
    {
      name: 'DIN D6 (@:paper-size.portrait)',
      dimensions: { x: 96, y: 136 }
    },
    {
      name: 'DIN D6 (@:paper-size.landscape)',
      dimensions: { x: 136, y: 96 }
    },
    {
      name: '@:paper-size.letter (@:paper-size.portrait)',
      dimensions: { x: 216, y: 279 }
    },
    {
      name: '@:paper-size.legal (@:paper-size.portrait)',
      dimensions: { x: 216, y: 356 }
    },
    {
      name: '@:paper-size.tabloid (@:paper-size.portrait)',
      dimensions: { x: 279, y: 432 }
    },
    {
      name: '@:paper-size.ledger (@:paper-size.portrait)',
      dimensions: { x: 432, y: 279 }
    },
    {
      name: '@:paper-size.junior-legal (@:paper-size.portrait)',
      dimensions: { x: 127, y: 203 }
    },
    {
      name: '@:paper-size.half-letter (@:paper-size.portrait)',
      dimensions: { x: 140, y: 216 }
    }
  ],
  actions: []
}
[2023-03-05T16:28:16.721Z] INFO (Http): { method: 'GET', path: '/preview' }
[2023-03-05T16:28:16.728Z] INFO (Process): { spawn: 'convert - -quality 75 jpg:-' }
```

**Additional context**

The logs contain another issue about an undefined process, I will open another ticket for that.

**Comment by sbs20** [comment]
Try using `afterDevices` in your local config and override the following values:

```
      pageHeight: 292,
      pageWidth: 215.8,
```

The app will just use the defaults reported by the scanner.

**Comment by CubicrootXYZ** [comment]
@sbs20 thanks for the very quick response. I am not exactly sure how I should set them, I tried the following 2 things:

```
      device.pageHeigth = 292;
      device.pageWidth = 208;
```
This results in a `scanimage: open of device epjitsu:libusb:001:007 failed: Invalid argument`

and 
```
      device.features['--pageHeigth'].default = 292;
      device.features['--pageWidth'].default = 208;
```
Which results in a `TypeError: Cannot set properties of undefined (setting 'default')`

Let me know if I am doing it wrong. This is my after scan method as far as it is working: 

```
  afterDevices(devices) {
    /**
     * Example code below
     */
    const device = devices.filter(d => d.id.startsWith('epjitsu'))[0];
    if (device) {
      device.features['--brightness'].default = 60;
      device.features['--contrast'].default = 85;
      device.features['--mode'].default = 'Color';
    }
  },
  ```

**Comment by sbs20** [comment]
This guess is correct:

```javascript
      device.features['--pageHeigth'].default = 292;
      device.features['--pageWidth'].default = 208;
```

But I think you have a typo in height. Should be:

```javascript
      device.features['--pageHeight'].default = 292;
      device.features['--pageWidth'].default = 208;
```

**Comment by CubicrootXYZ** [comment]
Unfortunately even without the typo I am getting the same error message. Tried each of them separate too, same behavior.

**Comment by sbs20** [comment]
Sorry - brain fail on my part:

```javascript
      device.features['--page-height'].default = 292;
      device.features['--page-width'].default = 208;
```

**Comment by CubicrootXYZ** [comment]
Thanks, that actually worked. I am really thankful for your time and help to get this up and running properly. Keep up your great work.
