### ISSUE TITLE
Process undefined for curl afterscan

### ISSUE THREAD

**Issue by CubicrootXYZ** [sbs20/scanservjs#576]
**Describe the bug**

I added the following afterscan and I am getting a "Process undefined" error:

```
  async afterScan(fileInfo) {
    // Copy the scan to the cloud
    return await Process.spawn(`curl -T '${fileInfo.fullname}' 'my_url/Dokumente/Scan/${fileInfo.fullname}' --user 'user:pass'`);
  },
```

I installed curl in the container and executed the command manually which worked without any issues. 

**To Reproduce**
1. Add the afterscan
2. Scan a file
3. Error pops up

**Expected behavior**

No error and uploaded file to webdav link.

**Screenshots**

**Client (please complete the following information):**
 - Browser: Firefox 110.0.1
 - Version: v2.26.0

**Server (please complete the following information):**
 - OS: Ubuntu 22.04
 - Docker: 23.0.1

Running the docker official docker image with `latest` tag.

**Logs**
 - Please include application logs (see commands below)
```
[2023-03-05T16:23:46.613Z] INFO (Http): { method: 'GET', path: '/preview' }
[2023-03-05T16:23:46.657Z] INFO (Process): { spawn: 'convert - -quality 75 jpg:-' }
[2023-03-05T16:23:50.574Z] INFO (Http): {
  method: 'POST',
  path: '/scan',
  body: {
    version: '2.26.0',
    params: {
      deviceId: 'epjitsu:libusb:001:006',
      resolution: 300,
      top: 0,
      pageHeight: 292,
      pageWidth: 215.8,
      mode: 'Color',
      source: 'ADF Front',
      brightness: 60,
      contrast: 85
    },
    filters: [],
    pipeline: 'PDF with OCR (OCRMYPDF | @:pipeline.high-quality)',
    batch: 'auto',
    index: 1
  }
}
[2023-03-05T16:23:50.583Z] INFO (ScanController): Scanning
[2023-03-05T16:23:50.585Z] INFO (Process): {
  spawn: "/usr/bin/scanimage -d epjitsu:libusb:001:006 --mode Color --source 'ADF Front' --resolution 300 --page-width 215.8 --page-height 292 -t 0 --format tiff --brightness 60 --contrast 85 --batch=data/temp/~tmp-scan-1-%04d.tif"
}
[2023-03-05T16:24:58.857Z] INFO (Process): {
  spawn: '/usr/bin/convert data/temp/~tmp-scan-1-0001.tif -scale 868 data/preview/preview.tif'
}
[2023-03-05T16:24:59.475Z] INFO (Process): { spawn: 'convert @- -quality 92 tmp-%04d.jpg && ls tmp-*.jpg' }
[2023-03-05T16:25:06.350Z] INFO (Process): { spawn: 'convert @- pdf:-' }
[2023-03-05T16:25:20.913Z] INFO (Process): {
  spawn: 'ocrmypdf -l eng --deskew --rotate-pages --rotate-pages-threshold 1.8 --optimize 2 --force-ocr - scan_0000.pdf'
}
[2023-03-05T16:27:26.856Z] INFO (Process): { spawn: 'ls scan_*.*' }
[2023-03-05T16:27:26.981Z] ERROR (Http): ReferenceError: Process is not defined
    at Object.afterScan (/app/config/config.local.js:73:5)
    at UserOptions.afterScan (/app/server/classes/user-options.js:41:31)
    at ScanController.execute (/app/server/scan-controller.js:179:25)
    at async Object.run (/app/server/scan-controller.js:203:12)
    at async Api.scan (/app/server/api.js:140:12)
    at async /app/server/configure.js:246:16
[2023-03-05T16:27:35.571Z] INFO (Http): { method: 'GET', path: '/files' }
[2023-03-05T16:27:35.572Z] INFO (Http): { method: 'GET', path: '/context' }
```

**Additional context**

**Comment by sbs20** [comment]
Documentation failure on my part I think. See this [sightly more complete example](https://github.com/sbs20/scanservjs/blob/master/docs/config.md#example-file)

In particular the first "require" line

**Comment by CubicrootXYZ** [comment]
Again thanks for the fast reply @sbs20. I did miss that import actually, for my setup with the docker container it actually had to be `const Process = require('../server/classes/process');`. Working now 🥳 .
